version: '3.8'

services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_HOST: database
      DATABASE_PORT: 5432
      DATABASE_NAME: myapp
      DATABASE_USER: myuser
      DATABASE_PASSWORD: mypassword
      NODE_ENV: development
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      - database
    ports:
      - "3000:3000"
    command: npm run start:dev
    networks:
      - app-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:3000
    command: npm run dev -- --host 0.0.0.0
    networks:
      - app-network

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
