# apps/frontend/Dockerfile.dev
FROM node:18-alpine

WORKDIR /app

# Copier les fichiers package.json
COPY package*.json ./
RUN npm install

# Copier le code source
COPY . .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]